version: "3.9"

services:
  nginx:
    build: ./nginx
    hostname: nginx_comunidad
    volumes:
      - ./static:/code/static
      - ./media:/code/media
    restart: always
    ports:
      - "81:80"
    networks:
      - backend

  web_pro:
    hostname: comunidad-web-pro
    container_name: comunidad-web-pro
    build: .
    env_file: .env
    volumes:
      - .:/app
    expose:
      - 8000
    depends_on:
      - db_pro
    networks:
      - backend

  db_pro:
    hostname: comunidad-db-pro
    container_name: comunidad-db-pro
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data-pro:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

volumes:
  db-data-pro:
networks:
  soporte_catedu_aragon_frontend:
    external: true
  backend:
    driver: bridge
