# Generated by Django 3.1.8 on 2021-04-15 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('books', '0002_auto_20210414_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksListingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Listado de libros de CATEDU',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BookIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('flat_menu', models.ForeignKey(blank=True, help_text='Si no está en la lista, se asignará automáticamente cuando crees la página', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_lateral', to='wagtailmenus.flatmenu')),
            ],
            options={
                'verbose_name': 'Índice de libro',
            },
            bases=('wagtailcore.page',),
        ),
    ]
