# Generated by Django 3.1.8 on 2021-04-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_bookindexpage_bookslistingpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookindexpage',
            name='flat_menu',
            field=models.CharField(blank=True, help_text='Si no está en la lista, se asignará automáticamente cuando crees la página', max_length=255, null=True),
        ),
    ]
