# Generated by Django 3.1.8 on 2021-04-16 10:50

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210416_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'h5', 'bold', 'italic', 'ol', 'ul', 'hr', 'link', 'document-link', 'image', 'embed', 'code', 'superscript', 'subscript', 'strikethrough', 'blockquote'], label='Contenido')), ('code', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.ChoiceBlock(choices=[('python', 'python'), ('javascript', 'javascript'), ('css', 'css'), ('markup', 'markup'), ('html', 'html'), ('go', 'go'), ('bash', 'bash')])), ('text', wagtail.core.blocks.TextBlock())], label='Code'))]),
        ),
    ]
